### ISSUE TITLE
Gerrit GitBlit Plugin for Gerrit 2.11.5

### ISSUE THREAD

**Issue by peterpakos** [tomaswolf/gerrit-gitblit-plugin#15]
Would it be possible to have a gitblit plugin integrating GitBlit 1.7.1 with Gerrit 2.11.5?

I've tried building gitblit plugin myself by following instructions at https://gerrit.googlesource.com/plugins/gitblit/+/stable-2.11 but failed miserably.

If it's not a secret, could you let me know how you made it compile OK?

Many thanks in advance.

**Comment by tomaswolf** [comment]
> ... have a gitblit plugin integrating GitBlit 1.7.1 with Gerrit 2.11.5

It is possible, but not simple. There's already issue #12 to update this plugin to Gitblit 1.7.1+. "+" because apparently 1.7.1 has at least one bug. I'm working on it in my free time, so don't hold your breath. In the meantime, what's wrong with the Gitblit 1.6.2-based plugin? There is one under "releases" [for Gerrit 2.11.5](https://github.com/tomaswolf/gerrit-gitblit-plugin/releases/tag/v2.11.3.162.2).

> ...how you made it compile OK?

This plugin here is a fork from the official one. That fork was made when the official plugin was super-buggy and based on a very old Gitblit version. Because this plugin here doesn't use Gitblit 1.7.1 but still 1.6.2, the build process differs quite a bit. For starters, I use maven, not buck. Second, I only use officially released maven bundles, no pre-releases.

**Comment by peterpakos** [comment]
Thanks for the info.

I've just installed the existing plugin v2.11.3.162.2 and the first thing that I've noticed that does not work properly is the owners column is completely empty in the repositories screen.

Is it a known bug?

If so, is there a way to disable this column?

**Comment by tomaswolf** [comment]
No, that was not a known bug.

Gitblit and Gerrit have different ideas about the "owners" of a repository. Gitblit therefore always thinks there were no owners set on a Gerrit-managed repository.

There is no way you as a user could disable this column.

I _could_ in theory change the Gitblit code in the plugin to not display that column and to ignore it on other pages, too. Or I _could_ try to make the plugin use Gerrit's ownership information. I prefer not to do either, though, as it would make future updates of Gitblit in the plugin more complicated. Note that Gerrit doesn't display project owners in its project list.

**Comment by peterpakos** [comment]
That's alright then, I think we can live with that.

I'll get this closed off now.

Thanks.
